#!/usr/bin/env zsh

git add -A

if [[ "$(uname)" == "Darwin" ]]; then
  sudo darwin-rebuild switch --flake ".#mac-${MACHINE}"
else
  sudo nix --extra-experimental-features "nix-command flakes" \
    run nixpkgs#home-manager -- \
    --extra-experimental-features "nix-command flakes" \
    switch --flake ".#linux-${MACHINE}"
fi
