#!/usr/bin/env zsh

git add -A

if [[ "$(uname)" == "Darwin" ]]; then
  sudo darwin-rebuild switch --flake ".#mac-${MACHINE}"
elif grep -q 'ID=nixos' /etc/os-release 2>/dev/null; then
  sudo nixos-rebuild switch --flake ".#nixos-${MACHINE}"
else
  nix --extra-experimental-features "nix-command flakes" \
    run nixpkgs#home-manager -- \
    --extra-experimental-features "nix-command flakes" \
    switch --flake ".#linux-${MACHINE}"
fi
